# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_function', models.CharField(max_length=200)),
                ('job_industry', models.CharField(max_length=200)),
                ('major_study', models.CharField(max_length=200)),
                ('city_location', models.CharField(max_length=200)),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
